GET http://localhost:3001/users

###
POST http://localhost:3001/register
Content-Type: application/json

{
    "username": "homer",
    "email": "donald@community.us",
    "password": "littlebigfoot"
}
